### PR TITLE
fix(nodeagent): memory leak, pprof inclusion and eliminating unnecessary goroutines

### LINKED ISSUE #72: Replace src-d dependencies

### PR DESCRIPTION
**Pull request by stebenz**

### CODE REVIEW

File: internal/operator/nodeagent/firewall/centos/ports.go [hunk 1]
```diff
@@ -12,52 +12,100 @@ func getAddAndRemovePorts(
...
 		}
-		addPorts = append(addPorts, fmt.Sprintf("--add-port=%s", desStr))
 	}
-closeloop:
-	for _, already := range alreadyOpen {
-		fields := strings.Split(already, "/")
-		port := fields[0]
-		protocol := fields[1]
+	//port that are not desired anymore
+	if alreadyOpen != nil && len(alreadyOpen) > 0 {
```
Comment (eliobischof) [inline internal/operator/nodeagent/firewall/centos/ports.go]: I think this branch is not necessary

File: internal/operator/nodeagent/firewall/centos/ports.go [hunk 2]
```diff
@@ -12,52 +12,100 @@ func getAddAndRemovePorts(
...
+				for _, desired := range desiredPorts {
+					if desired.Port == port && desired.Protocol == protocol {
+						found = true
+						break
+					}
+				}
+			}
+
+			if !found {
+				if alwaysOpen != nil && len(alwaysOpen) > 0 {
```
Comment (eliobischof) [inline internal/operator/nodeagent/firewall/centos/ports.go]: this neighter

File: internal/operator/nodeagent/firewall/centos/ports.go [hunk 3]
```diff
@@ -12,52 +12,100 @@ func getAddAndRemovePorts(
...
+			fields := strings.Split(open, "/")
+			port := fields[0]
+			protocol := fields[1]
+
+			current.FW = append(current.FW, &common.Allowed{
+				Port:     port,
+				Protocol: protocol,
+			})
+
+			if desiredPorts != nil && len(desiredPorts) > 0 {
```
Comment (eliobischof) [inline internal/operator/nodeagent/firewall/centos/ports.go]: and this

File: internal/operator/nodeagent/iterator.go [hunk 4]
```diff
@@ -106,6 +106,11 @@ func Iterator(
 			panic(err)
 		}
 
+		/*query := func() (func() error, error) {
+			return doQuery(*naDesired, curr)
+		}
+
+		ensure, err := QueryFuncGoroutine(query)*/
```
Comment (eliobischof) [inline internal/operator/nodeagent/iterator.go:111]:
```suggestion
```

File: internal/operator/nodeagent/firewall/centos/centOS.go [hunk 5]
```diff
@@ -21,7 +21,12 @@ func Ensurer(monitor mntr.Monitor, ignore []string) nodeagent.FirewallEnsurer {
 		}
 
 		for name, _ := range desired.Zones {
-			currentZone, ensureFunc, err := ensureZone(monitor, name, desired, ignore)
+
+			/*ensure := func() (*common.ZoneDesc, func() error, error) {
+				return ensureZone(monitor, name, desired, ignore)
+			}
+			currentZone, ensureFunc, err := goroutineEnsureZone(ensure)*/
```
Comment (eliobischof) [inline internal/operator/nodeagent/firewall/centos/centOS.go]:
```suggestion
```

File: internal/operator/orbiter/kinds/providers/gce/computesservice.go [hunk 6]
```diff
@@ -272,8 +288,16 @@ func (m *machinesService) instances() (map[string][]*instance, error) {
...
 
-	m.cache.instances = make(map[string][]*instance)
+	if m.cache.instances == nil {
+		m.cache.instances = make(map[string][]*instance)
+	} else {
+		for k := range m.cache.instances {
+			m.cache.instances[k] = nil
+			delete(m.cache.instances, k)
+		}
+	}
```
Comment (eliobischof) [inline internal/operator/orbiter/kinds/providers/gce/computesservice.go]: this is never true

File: internal/operator/orbiter/kinds/providers/gce/gcemachine.go [hunk 7]
```diff
@@ -44,6 +44,7 @@ func (c *gceMachine) Execute(stdin io.Reader, command string) ([]byte, error) {
 
 func (c *gceMachine) execute(stdin io.Reader, command string) (outBuf *bytes.Buffer, err error) {
 	outBuf = new(bytes.Buffer)
+	defer outBuf.Reset()
```
Comment (eliobischof) [inline internal/operator/orbiter/kinds/providers/gce/gcemachine.go]: I think this breaks local orbctl commands on GCE

```suggestion
```

**Review by eliobischof — CHANGES_REQUESTED** [review]

File: internal/operator/orbiter/kinds/providers/gce/computesservice.go (hunk 6 above)
Comment (stebenz) [reply internal/operator/orbiter/kinds/providers/gce/computesservice.go]: it can be true, as the cache is only used in this file and the map is only defined in this if. So there is a possibility that the slice is nil if the slice is no initialized while defining the machineService.

**Review by eliobischof — APPROVED** [review]
